repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      - id: ruff-format
      - id: ruff
        args: [ "--fix", "--show-fixes"]
        types_or: [python, pyi]
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.2  # uv version.
    hooks:
    - id: uv-lock
